version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - composer install
  post_build:
    commands:
      - php artisan cache:clear
     
      
artifacts:
  files:
    - '**/*'
  name: laravel.zip
    
