name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on:  ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Installating php7.3
      run: sudo apt -y install php7.3 -y
      
    - name: Installating php extensions
      run: sudo apt-get install -y php7.3-imagick php7.3-cli php7.3-json php7.3-common php7.3-mysql php7.3-zip php7.3-gd php7.3-mbstring php7.3-curl php7.3-xml
   
    - name: remove composer.lock
      run: rm composer.lock
      
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        php_version: "7.3"
        args: --no-plugins allow-plugins.kylekatarnls/update false --prefer-dist --no-progress
   

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
